name: workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    environment: secrets
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mailsender:latest .

  deploy:
    needs: build
    runs-on: self-hosted
    environment: secrets
    steps:
      - name: Stop old container if exists
        run: |
          if docker ps -a --format '{{.Names}}' | grep -Eq '^mailsender$'; then
            docker stop mailsender
            docker rm mailsender
          fi

      - name: Run new container
        run: |
          docker run -d \
            --name mailsender \
            --restart unless-stopped \
            --memory=200m \
            -e CODE_CACHE_SIZE="${{ secrets.CODE_CACHE_SIZE }}" \
            -e CODE_LIFE_TIME="${{ secrets.CODE_LIFE_TIME }}" \
            -e MAIL_HOST="${{ secrets.MAIL_HOST }}" \
            -e MAIL_PORT="${{ secrets.MAIL_PORT }}" \
            -e MAIL_USERNAME="${{ secrets.MAIL_USERNAME }}" \
            -e MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}" \
            -e PORT="${{ secrets.PORT }}" \
            -p 8080:8080 \
            mailsender:latest

      - name: Check container logs
        run: docker logs mailsender --tail 50